spring:
  application:
    name: service-a
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0